using Community.LiteDB.Aot.SourceGenerators.Models;
using System.Text;
using System.Linq;
using System.Globalization;
using System.Collections.Generic;

namespace Community.LiteDB.Aot.SourceGenerators.Helpers;

internal static class CodeGenerator
{
    /// <summary>
    /// Generates the complete mapper class for an entity
    /// </summary>
    public static string GenerateMapper(EntityInfo entity)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using LiteDB;");
        sb.AppendLine("using Community.LiteDB.Aot.Mapping;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entity.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated mapper for {entity.Name}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"internal sealed class {entity.Name}Mapper : IEntityMapper<{entity.Name}>");
        sb.AppendLine("{");

        // CollectionName property
        sb.AppendLine($"    public string CollectionName => \"{entity.CollectionName}\";");
        sb.AppendLine($"    public string IdFieldName => \"_id\";");
        sb.AppendLine();

        // Serialize method
        GenerateSerializeMethod(sb, entity);
        sb.AppendLine();

        // Deserialize method
        GenerateDeserializeMethod(sb, entity);
        sb.AppendLine();

        // GetId method
        GenerateGetIdMethod(sb, entity);
        sb.AppendLine();

        // SetId method
        GenerateSetIdMethod(sb, entity);

        // Generate nested object helper methods
        GenerateNestedObjectHelpers(sb, entity);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateNestedObjectHelpers(StringBuilder sb, EntityInfo entity)
    {
        // Collect all nested types at all depths
        var allNestedTypes = CollectAllNestedTypes(entity.NestedTypes);

        if (!allNestedTypes.Any())
            return;

        sb.AppendLine();
        sb.AppendLine("    // Nested object serialization helpers");

        // Sort by depth to generate deeper types first (they don't have dependencies)
        var sortedTypes = allNestedTypes
            .OrderByDescending(kvp => kvp.Value.Depth)
            .ThenBy(kvp => kvp.Key)
            .ToList();

        foreach (var kvp in sortedTypes)
        {
            var nestedTypeName = kvp.Key;
            var nestedTypeInfo = kvp.Value;

            GenerateNestedObjectSerializer(sb, nestedTypeName, nestedTypeInfo, entity);
            sb.AppendLine();
            GenerateNestedObjectDeserializer(sb, nestedTypeName, nestedTypeInfo, entity);
        }
    }

    private static Dictionary<string, NestedTypeInfo> CollectAllNestedTypes(Dictionary<string, NestedTypeInfo> nestedTypes)
    {
        var result = new Dictionary<string, NestedTypeInfo>();

        foreach (var kvp in nestedTypes)
        {
            var name = kvp.Key;
            var info = kvp.Value;

            // Add this type
            if (!result.ContainsKey(name))
            {
                result[name] = info;
            }

            // Recursively add nested types within this type
            if (info.NestedTypes.Any())
            {
                var innerTypes = CollectAllNestedTypes(info.NestedTypes);
                foreach (var innerKvp in innerTypes)
                {
                    var innerName = innerKvp.Key;
                    var innerInfo = innerKvp.Value;

                    if (!result.ContainsKey(innerName))
                    {
                        result[innerName] = innerInfo;
                    }
                }
            }
        }

        return result;
    }

    private static void GenerateNestedObjectSerializer(StringBuilder sb, string nestedTypeName, NestedTypeInfo nestedTypeInfo, EntityInfo entity)
    {
        sb.AppendLine($"    private static BsonDocument SerializeNested{nestedTypeName}({nestedTypeName} obj)");
        sb.AppendLine("    {");
        sb.AppendLine("        var doc = new BsonDocument();");

        // Serialize each property
        foreach (var prop in nestedTypeInfo.Properties)
        {
            var fieldName = string.IsNullOrEmpty(prop.BsonFieldName) ? prop.Name : prop.BsonFieldName;

            // Handle nested objects within nested objects
            if (prop.IsNestedObject && !string.IsNullOrEmpty(prop.NestedTypeName))
            {
                if (prop.IsNullable || prop.TypeName == "string" || prop.TypeName == "String")
                {
                    sb.AppendLine($"        if (obj.{prop.Name} != null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            doc[\"{fieldName}\"] = SerializeNested{prop.NestedTypeName}(obj.{prop.Name});");
                    sb.AppendLine("        }");
                }
                else
                {
                    sb.AppendLine($"        doc[\"{fieldName}\"] = SerializeNested{prop.NestedTypeName}(obj.{prop.Name});");
                }
            }
            // Handle regular properties
            else if (prop.IsNullable || prop.TypeName == "string" || prop.TypeName == "String")
            {
                sb.AppendLine($"        if (obj.{prop.Name} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            doc[\"{fieldName}\"] = {GetBsonValueConversion($"obj.{prop.Name}", prop.TypeName, prop.IsNullable, prop.IsCollection, prop.CollectionItemType)};");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        doc[\"{fieldName}\"] = {GetBsonValueConversion($"obj.{prop.Name}", prop.TypeName, prop.IsNullable, prop.IsCollection, prop.CollectionItemType)};");
            }
        }

        sb.AppendLine("        return doc;");
        sb.AppendLine("    }");
    }

    private static void GenerateNestedObjectDeserializer(StringBuilder sb, string nestedTypeName, NestedTypeInfo nestedTypeInfo, EntityInfo entity)
    {
        sb.AppendLine($"    private static {nestedTypeName}? DeserializeNested{nestedTypeName}(BsonDocument doc)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {nestedTypeName}");
        sb.AppendLine("        {");

        // Deserialize each property
        var lastProp = nestedTypeInfo.Properties.LastOrDefault();
        foreach (var prop in nestedTypeInfo.Properties)
        {
            var fieldName = string.IsNullOrEmpty(prop.BsonFieldName) ? prop.Name : prop.BsonFieldName;
            var isLast = prop == lastProp;
            var comma = isLast ? "" : ",";

            // Handle nested objects within nested objects
            if (prop.IsNestedObject && !string.IsNullOrEmpty(prop.NestedTypeName))
            {
                sb.AppendLine($"            {prop.Name} = doc.ContainsKey(\"{fieldName}\") && !doc[\"{fieldName}\"].IsNull");
                sb.AppendLine($"                ? DeserializeNested{prop.NestedTypeName}(doc[\"{fieldName}\"].AsDocument)");
                sb.AppendLine($"                : null{comma}");
            }
            // Handle regular properties
            else if (prop.IsNullable || prop.TypeName == "string" || prop.TypeName == "String")
            {
                sb.AppendLine($"            {prop.Name} = doc.ContainsKey(\"{fieldName}\") && !doc[\"{fieldName}\"].IsNull");
                sb.AppendLine($"                ? {GetBsonValueExtraction($"doc[\"{fieldName}\"]", prop.TypeName, prop.IsNullable, prop.IsCollection, prop.CollectionItemType)}");
                sb.AppendLine($"                : null{comma}");
            }
            else
            {
                sb.AppendLine($"            {prop.Name} = doc.ContainsKey(\"{fieldName}\")");
                sb.AppendLine($"                ? {GetBsonValueExtraction($"doc[\"{fieldName}\"]", prop.TypeName, prop.IsNullable, prop.IsCollection, prop.CollectionItemType)}");
                sb.AppendLine($"                : default{comma}");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void GenerateSerializeMethod(StringBuilder sb, EntityInfo entity)
    {
        sb.AppendLine($"    public BsonDocument Serialize({entity.Name} entity)");
        sb.AppendLine("    {");

        // Add validation for required/attributed properties
        bool hasValidation = entity.Properties.Any(p =>
            p.IsRequired || p.MaxLength.HasValue || p.MinLength.HasValue ||
            p.RangeMin != null || p.RangeMax != null);

        if (hasValidation)
        {
            GenerateValidation(sb, entity);
            sb.AppendLine();
        }

        sb.AppendLine("        var doc = new BsonDocument();");
        sb.AppendLine();

        // ID field - only if not default value
        if (entity.IdProperty != null)
        {
            var defaultCheck = GetDefaultValueCheck(entity.IdProperty.TypeName, entity.IdProperty.IsNullable);
            sb.AppendLine($"        // Only include _id if not default value");
            sb.AppendLine($"        if (entity.{entity.IdProperty.Name} != {defaultCheck})");
            sb.AppendLine("        {");
            sb.AppendLine($"            doc[\"_id\"] = {GetBsonValueConversion($"entity.{entity.IdProperty.Name}", entity.IdProperty.TypeName, entity.IdProperty.IsNullable, entity.IdProperty.IsCollection, entity.IdProperty.CollectionItemType)};");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Other properties
        foreach (var prop in entity.Properties)
        {
            if (entity.IgnoredProperties.Contains(prop.Name))
                continue;

            if (prop.Name == entity.IdProperty?.Name)
                continue; // Already handled

            // Skip read-only properties in serialization
            if (prop.IsReadOnly)
            {
                sb.AppendLine($"        // Property '{prop.Name}' is read-only - skipped in serialization");
                continue;
            }

            var fieldName = string.IsNullOrEmpty(prop.BsonFieldName) ? prop.Name : prop.BsonFieldName;

            // Handle nested objects
            if (prop.IsNestedObject && !string.IsNullOrEmpty(prop.NestedTypeName))
            {
                if (prop.IsNullable || prop.TypeName == "string" || prop.TypeName == "String")
                {
                    sb.AppendLine($"        if (entity.{prop.Name} != null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            doc[\"{fieldName}\"] = SerializeNested{prop.NestedTypeName}(entity.{prop.Name});");
                    sb.AppendLine("        }");
                }
                else
                {
                    sb.AppendLine($"        doc[\"{fieldName}\"] = SerializeNested{prop.NestedTypeName}(entity.{prop.Name});");
                }
                continue;
            }

            // Handle regular properties
            if (prop.IsNullable || prop.TypeName == "string" || prop.TypeName == "String")
            {
                sb.AppendLine($"        if (entity.{prop.Name} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            doc[\"{fieldName}\"] = {GetBsonValueConversion($"entity.{prop.Name}", prop.TypeName, prop.IsNullable, prop.IsCollection, prop.CollectionItemType)};");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        doc[\"{fieldName}\"] = {GetBsonValueConversion($"entity.{prop.Name}", prop.TypeName, prop.IsNullable, prop.IsCollection, prop.CollectionItemType)};");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return doc;");
        sb.AppendLine("    }");
    }
    
    private static void GenerateValidation(StringBuilder sb, EntityInfo entity)
    {
        sb.AppendLine("        // Validation from Data Annotations");

        foreach (var prop in entity.Properties)
        {
            if (entity.IgnoredProperties.Contains(prop.Name))
                continue;

            // Required validation
            if (prop.IsRequired && (prop.IsNullable || prop.TypeName == "string" || prop.TypeName == "String"))
            {
                sb.AppendLine($"        if (entity.{prop.Name} == null)");
                sb.AppendLine($"            throw new ArgumentNullException(nameof(entity), \"Property '{prop.Name}' is required\");");
            }

            // String length validation
            if (prop.TypeName == "string" || prop.TypeName == "String")
            {
                if (prop.MinLength.HasValue)
                {
                    sb.AppendLine($"        if (entity.{prop.Name} != null && entity.{prop.Name}.Length < {prop.MinLength.Value})");
                    sb.AppendLine($"            throw new ArgumentException(\"Property '{prop.Name}' must be at least {prop.MinLength.Value} characters long\", nameof(entity));");
                }

                if (prop.MaxLength.HasValue)
                {
                    sb.AppendLine($"        if (entity.{prop.Name} != null && entity.{prop.Name}.Length > {prop.MaxLength.Value})");
                    sb.AppendLine($"            throw new ArgumentException(\"Property '{prop.Name}' must not exceed {prop.MaxLength.Value} characters\", nameof(entity));");
                }
            }


            // Range validation (for numeric types)
            if (prop.RangeMin != null && prop.RangeMax != null)
            {
                var typeName = prop.TypeName.TrimEnd('?');
                if (typeName == "int" || typeName == "Int32" || typeName == "long" || typeName == "Int64" ||
                    typeName == "double" || typeName == "Double" || typeName == "decimal" || typeName == "Decimal")
                {
                    // Format numbers using invariant culture to avoid comma/period issues
                    var minStr = FormatNumber(prop.RangeMin);
                    var maxStr = FormatNumber(prop.RangeMax);

                    sb.AppendLine($"        if (entity.{prop.Name} < {minStr} || entity.{prop.Name} > {maxStr})");
                    sb.AppendLine($"            throw new ArgumentOutOfRangeException(nameof(entity), \"Property '{prop.Name}' must be between {minStr} and {maxStr}\");");
                }
            }
        }
    }

    private static void GenerateDeserializeMethod(StringBuilder sb, EntityInfo entity)
    {
        sb.AppendLine($"    public {entity.Name} Deserialize(BsonDocument doc)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {entity.Name}");
        sb.AppendLine("        {");

        // ID property
        if (entity.IdProperty != null)
        {
            sb.AppendLine($"            {entity.IdProperty.Name} = {GetBsonValueExtraction("doc[\"_id\"]", entity.IdProperty.TypeName)},");
        }

        // Other properties
        var lastProp = entity.Properties.LastOrDefault();
        foreach (var prop in entity.Properties)
        {
            if (entity.IgnoredProperties.Contains(prop.Name))
                continue;

            if (prop.Name == entity.IdProperty?.Name)
                continue;

            var fieldName = string.IsNullOrEmpty(prop.BsonFieldName) ? prop.Name : prop.BsonFieldName;
            var isLast = prop == lastProp;
            var comma = isLast ? "" : ",";


            // Handle nested objects
            if (prop.IsNestedObject && !string.IsNullOrEmpty(prop.NestedTypeName))
            {
                sb.AppendLine($"            {prop.Name} = doc.ContainsKey(\"{fieldName}\") && !doc[\"{fieldName}\"].IsNull");
                sb.AppendLine($"                ? DeserializeNested{prop.NestedTypeName}(doc[\"{fieldName}\"].AsDocument)");
                sb.AppendLine($"                : null{comma}");
            }
            // Handle regular properties
            else if (prop.IsNullable)
            {
                sb.AppendLine($"            {prop.Name} = doc.ContainsKey(\"{fieldName}\") ? {GetBsonValueExtraction($"doc[\"{fieldName}\"]", prop.TypeName)} : null{comma}");
            }
            else
            {
                sb.AppendLine($"            {prop.Name} = {GetBsonValueExtraction($"doc[\"{fieldName}\"]", prop.TypeName)}{comma}");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void GenerateGetIdMethod(StringBuilder sb, EntityInfo entity)
    {
        if (entity.IdProperty != null)
        {
            sb.AppendLine($"    public BsonValue GetId({entity.Name} entity)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return {GetBsonValueConversion($"entity.{entity.IdProperty.Name}", entity.IdProperty.TypeName)};");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public BsonValue GetId({entity.Name} entity)");
            sb.AppendLine("    {");
            sb.AppendLine($"        throw new NotSupportedException(\"Entity {entity.Name} has no ID property configured.\");");
            sb.AppendLine("    }");
        }
    }

    private static void GenerateSetIdMethod(StringBuilder sb, EntityInfo entity)
    {
        if (entity.IdProperty != null)
        {
            sb.AppendLine($"    public void SetId({entity.Name} entity, BsonValue id)");
            sb.AppendLine("    {");
            sb.AppendLine($"        entity.{entity.IdProperty.Name} = {GetBsonValueExtraction("id", entity.IdProperty.TypeName)};");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public void SetId({entity.Name} entity, BsonValue id)");
            sb.AppendLine("    {");
            sb.AppendLine($"        // No ID property to set");
            sb.AppendLine("    }");
        }
    }

    /// <summary>
    /// Generates code to convert C# value to BsonValue
    /// </summary>
    private static string GetBsonValueConversion(string valueExpression, string typeName, bool isNullable = false, bool isCollection = false, string? collectionItemType = null)
    {
        // Handle collections first
        if (isCollection && collectionItemType != null)
        {
            return $"new BsonArray({valueExpression}.Select(item => {GetBsonValueConversion("item", collectionItemType)}))";
        }

        // Handle nullable wrapper
        var expression = typeName switch
        {
            // Primitives
            "int" or "Int32" or "int?" or "Int32?" => $"new BsonValue({valueExpression})",
            "long" or "Int64" or "long?" or "Int64?" => $"new BsonValue({valueExpression})",
            "bool" or "Boolean" or "bool?" or "Boolean?" => $"new BsonValue({valueExpression})",
            "double" or "Double" or "double?" or "Double?" => $"new BsonValue({valueExpression})",
            "float" or "Single" or "float?" or "Single?" => $"new BsonValue((double){valueExpression})",
            "decimal" or "Decimal" or "decimal?" or "Decimal?" => $"new BsonValue({valueExpression})",
            "byte" or "Byte" or "byte?" or "Byte?" => $"new BsonValue((int){valueExpression})",
            "short" or "Int16" or "short?" or "Int16?" => $"new BsonValue((int){valueExpression})",

            // String (always nullable reference)
            "string" or "String" => $"new BsonValue({valueExpression})",

            // Date/Time
            "DateTime" or "DateTime?" => $"new BsonValue({valueExpression})",
            "DateTimeOffset" or "DateTimeOffset?" => $"new BsonValue({valueExpression}.DateTime)",

            // Guid
            "Guid" or "Guid?" => $"new BsonValue({valueExpression})",

            // Binary
            "byte[]" => $"new BsonValue({valueExpression})",

            // Enum (will be converted to int or string based on settings)
            _ when typeName.EndsWith("?") => $"new BsonValue((int){valueExpression})", // Enum nullable
            _ => $"new BsonValue({valueExpression})" // Default - assume enum or convertible
        };

        return expression;
    }

    /// <summary>
    /// Generates code to serialize a nested object to BsonDocument
    /// </summary>
    private static string SerializeNestedObject(string valueExpression, string typeName, EntityInfo? nestedEntity = null)
    {
        // For now, generate inline serialization
        // TODO: Could optimize by generating separate mapper for nested type
        return $"SerializeNested_{typeName}({valueExpression})";
    }

    /// <summary>
    /// Generates code to extract value from BsonValue
    /// </summary>
    private static string GetBsonValueExtraction(string bsonExpression, string typeName, bool isNullable = false, bool isCollection = false, string? collectionItemType = null)
    {
        // Handle collections first
        if (isCollection && collectionItemType != null)
        {
            var itemExtraction = GetBsonValueExtraction("item", collectionItemType);
            return $"{bsonExpression}.AsArray.Select(item => {itemExtraction}).ToList()";
        }

        var extraction = typeName switch
        {
            // Primitives
            "int" or "Int32" => $"{bsonExpression}.AsInt32",
            "int?" or "Int32?" => $"{bsonExpression}.IsNull ? (int?)null : {bsonExpression}.AsInt32",
            "long" or "Int64" => $"{bsonExpression}.AsInt64",
            "long?" or "Int64?" => $"{bsonExpression}.IsNull ? (long?)null : {bsonExpression}.AsInt64",
            "bool" or "Boolean" => $"{bsonExpression}.AsBoolean",
            "bool?" or "Boolean?" => $"{bsonExpression}.IsNull ? (bool?)null : {bsonExpression}.AsBoolean",
            "double" or "Double" => $"{bsonExpression}.AsDouble",
            "double?" or "Double?" => $"{bsonExpression}.IsNull ? (double?)null : {bsonExpression}.AsDouble",
            "float" or "Single" => $"(float){bsonExpression}.AsDouble",
            "float?" or "Single?" => $"{bsonExpression}.IsNull ? (float?)null : (float){bsonExpression}.AsDouble",
            "decimal" or "Decimal" => $"{bsonExpression}.AsDecimal",
            "decimal?" or "Decimal?" => $"{bsonExpression}.IsNull ? (decimal?)null : {bsonExpression}.AsDecimal",
            "byte" or "Byte" => $"(byte){bsonExpression}.AsInt32",
            "byte?" or "Byte?" => $"{bsonExpression}.IsNull ? (byte?)null : (byte){bsonExpression}.AsInt32",
            "short" or "Int16" => $"(short){bsonExpression}.AsInt32",
            "short?" or "Int16?" => $"{bsonExpression}.IsNull ? (short?)null : (short){bsonExpression}.AsInt32",

            // String
            "string" or "String" => $"{bsonExpression}.AsString",

            // Date/Time
            "DateTime" => $"{bsonExpression}.AsDateTime",
            "DateTime?" => $"{bsonExpression}.IsNull ? (DateTime?)null : {bsonExpression}.AsDateTime",
            "DateTimeOffset" => $"new DateTimeOffset({bsonExpression}.AsDateTime)",
            "DateTimeOffset?" => $"{bsonExpression}.IsNull ? (DateTimeOffset?)null : new DateTimeOffset({bsonExpression}.AsDateTime)",

            // Guid
            "Guid" => $"{bsonExpression}.AsGuid",
            "Guid?" => $"{bsonExpression}.IsNull ? (Guid?)null : {bsonExpression}.AsGuid",

            // Binary
            "byte[]" => $"{bsonExpression}.AsBinary",

            // Enum (assume int-based)
            _ when typeName.EndsWith("?") => $"{bsonExpression}.IsNull ? ({typeName})null : ({typeName.TrimEnd('?')}){bsonExpression}.AsInt32",
            _ => $"({typeName}){bsonExpression}.AsInt32" // Default - assume enum
        };

        return extraction;
    }

    /// <summary>
    /// Gets default value check for a type
    /// </summary>
    private static string GetDefaultValueCheck(string typeName, bool isNullable)
    {
        if (isNullable || typeName == "string" || typeName == "String")
        {
            return "null";
        }

        return typeName switch
        {
            "int" or "Int32" or "long" or "Int64" or "byte" or "Byte" or "short" or "Int16" => "0",
            "bool" or "Boolean" => "false",
            "Guid" => "Guid.Empty",
            "DateTime" => "DateTime.MinValue",
            "DateTimeOffset" => "DateTimeOffset.MinValue",
            _ => "default"
        };
    }

    /// <summary>
    /// Generates the RegisterMappers partial method
    /// </summary>
    public static string GenerateDbContextPartial(DbContextInfo context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Community.LiteDB.Aot.Mapping;");

        // Add using statements for entity namespaces
        var entityNamespaces = context.Entities
            .Select(e => e.Namespace)
            .Distinct()
            .Where(ns => ns != context.Namespace) // Don't add using for same namespace
            .OrderBy(ns => ns);

        foreach (var ns in entityNamespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {context.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated partial class for {context.ClassName}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"partial class {context.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated mapper registration");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected override void RegisterMappers()");
        sb.AppendLine("    {");

        foreach (var entity in context.Entities)
        {
            sb.AppendLine($"        RegisterMapper(new {entity.Name}Mapper());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Formats a number using invariant culture to avoid locale-specific issues
    /// </summary>
    private static string FormatNumber(object value)
    {
        return value switch
        {
            int i => i.ToString(CultureInfo.InvariantCulture),
            long l => l.ToString(CultureInfo.InvariantCulture) + "L",
            double d => d.ToString("G", CultureInfo.InvariantCulture),
            decimal dec => dec.ToString(CultureInfo.InvariantCulture) + "m",
            float f => f.ToString("G", CultureInfo.InvariantCulture) + "f",
            _ => value.ToString() ?? "0"
        };
    }

    /// <summary>
    /// Formats a number with cast to target type
    /// </summary>
    private static string FormatNumberWithCast(object value, string targetTypeName)
    {
        var formattedValue = FormatNumber(value);

        // If value and target types don't match, add cast
        var valueIsDecimal = value is decimal;
        var valueIsDouble = value is double;
        var targetIsDecimal = targetTypeName == "decimal" || targetTypeName == "Decimal";
        var targetIsDouble = targetTypeName == "double" || targetTypeName == "Double";

        // decimal property with double attribute value: cast to decimal
        if (targetIsDecimal && valueIsDouble)
        {
            // Remove 'd' suffix if present and add 'm'
            formattedValue = formattedValue.TrimEnd('d', 'D') + "m";
        }
        // double property with decimal attribute value: remove 'm' suffix
        else if (targetIsDouble && valueIsDecimal)
        {
            formattedValue = formattedValue.TrimEnd('m', 'M');
        }

        return formattedValue;
    }
}
